apiVersion: batch/v1
kind: CronJob
metadata:
  name: anniversary
  namespace: nyan
spec:
  schedule: "0 10 * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: anniversary
        spec:
          restartPolicy: Never
          containers:
          - name: anniversary
            image: commojun/nyanbot:0.0.11
            command: ["nyan", "anniversary"]
            envFrom:
            - secretRef:
                name: nyan-secret
