apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: nyan
spec:
  selector:
    app: redis
  ports:
  - name: http
    port: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: nyan
  labels:
    app: redis
spec:
  restartPolicy: Always
  containers:
  - name: redis
    image: redis:6.2
    ports:
    - containerPort: 6379

