apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: nyan
spec:
  type: NodePort
  selector:
    app: server
  ports:
  - name: http
    port: 30001
    targetPort: 30001
    nodePort: 30001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: nyan
  labels:
    deploy: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: commojun/nyanbot:0.0.11
        ports:
        - containerPort: 30001
        command: ["nyan", "server"]
        envFrom:
        - secretRef:
            name: nyan-secret
        lifecycle:
          postStart:
            exec:
              command: ["nyan", "export"]

